# @server= http://tickettric.dev
@server=http://localhost:2000
### sign up
POST {{server}}/api/users/signup
Content-Type: application/json

{
    "email": "kgtwf@yahoo.com",
    "password": "j2hdb#eiur"
}

### sign up
GET {{server}}/api/users/currentUser/cfgbhhgc

##### homepage
GET {{server}}

##############  TICKETS  ##################
POST {{server}}/api/tickets
Content-Type: application/json

{
    "title": "ballu",
    "price": "20"
}