apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-c
          image: jewelcodes/auth:latest
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: JWT_KEY
            - name: DATABASE_URL_AUTH
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: DATABASE_URL_AUTH
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: auth-port
                  key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 2000
      targetPort: 2000
